# -*- coding: utf-8 -*-

"""
Enumerate all built-in ICON images.
"""

import os

dir_icons = os.path.join(os.path.dirname(os.path.abspath(__file__)), "icons")

class IconFileEnum:
    """
    List of built-in icon files.
    """
    dictionary = os.path.join(dir_icons, "dictionary-96.png")
    search = os.path.join(dir_icons, "search-96.png")
    refresh = os.path.join(dir_icons, "refresh-96.png")
    landline = os.path.join(dir_icons, "landline-96.png")
    pause = os.path.join(dir_icons, "pause-96.png")
    folder = os.path.join(dir_icons, "folder-96.png")
    trash = os.path.join(dir_icons, "trash-96.png")
    calendar = os.path.join(dir_icons, "calendar-96.png")
    start = os.path.join(dir_icons, "start-96.png")
    idea = os.path.join(dir_icons, "idea-96.png")
    mail = os.path.join(dir_icons, "mail-96.png")
    password = os.path.join(dir_icons, "password-96.png")
    meeting = os.path.join(dir_icons, "meeting-96.png")
    error = os.path.join(dir_icons, "error-96.png")
    code = os.path.join(dir_icons, "code-96.png")
    microsoft_word = os.path.join(dir_icons, "microsoft-word-96.png")
    flask = os.path.join(dir_icons, "flask-96.png")
    internet = os.path.join(dir_icons, "internet-96.png")
    reset = os.path.join(dir_icons, "reset-96.png")
    task = os.path.join(dir_icons, "task-96.png")
    microsoft_powerpoint = os.path.join(dir_icons, "microsoft-powerpoint-96.png")
    groupchat = os.path.join(dir_icons, "groupchat-96.png")
    question = os.path.join(dir_icons, "question-96.png")
    chat = os.path.join(dir_icons, "chat-96.png")
    plus = os.path.join(dir_icons, "plus-96.png")
    bash = os.path.join(dir_icons, "bash-96.png")
    archive_folder = os.path.join(dir_icons, "archive-folder-96.png")
    info = os.path.join(dir_icons, "info-96.png")
    console = os.path.join(dir_icons, "console-96.png")
    star = os.path.join(dir_icons, "star-96.png")
    upload = os.path.join(dir_icons, "upload-96.png")
    download = os.path.join(dir_icons, "download-96.png")
    android = os.path.join(dir_icons, "android-96.png")
    minus = os.path.join(dir_icons, "minus-96.png")
    iphone = os.path.join(dir_icons, "iphone-96.png")
    check = os.path.join(dir_icons, "check-96.png")
    file = os.path.join(dir_icons, "file-96.png")
    box = os.path.join(dir_icons, "box-96.png")
    laptop = os.path.join(dir_icons, "laptop-96.png")
    undo = os.path.join(dir_icons, "undo-96.png")
    microsoft_excel = os.path.join(dir_icons, "microsoft-excel-96.png")
    gear = os.path.join(dir_icons, "gear-96.png")
    rocket = os.path.join(dir_icons, "rocket-96.png")
    stop = os.path.join(dir_icons, "stop-96.png")
    redo = os.path.join(dir_icons, "redo-96.png")
    debug = os.path.join(dir_icons, "debug-96.png")
    desktop = os.path.join(dir_icons, "desktop-96.png")
    git = os.path.join(dir_icons, "git-96.png")
    id_card = os.path.join(dir_icons, "id-card-96.png")
    message = os.path.join(dir_icons, "message-96.png")
    bookmark = os.path.join(dir_icons, "bookmark-96.png")
    explosion = os.path.join(dir_icons, "explosion-96.png")
    close = os.path.join(dir_icons, "close-96.png")
    todo = os.path.join(dir_icons, "todo-96.png")
    remove = os.path.join(dir_icons, "remove-96.png")
    fire = os.path.join(dir_icons, "fire-96.png")
